// vuejs/increment/src/App.vue
<template>
  <img alt="logo" src="./assets/logo.svg">

  <!-- Not Connected -->
  <div class="content" v-if="!accounts">
    <!-- Controls -->
    <div class="button-controls">
      <!-- Connect -->
      <button id="connect" class="btn btn-main" @click="connectWallet();">Connect Wallet</button>
    </div>
  </div>

  <!-- Connected -->
  <div class="content" v-else>

    <!-- Status Display / User Feedback -->
    <div class="status-display" v-if="!isNaN(counter)">
      <ul class="status">
        <li class="counter"><strong>Counter:</strong>&nbsp;{{counter}}</li>
      </ul>
    </div>

    <!-- Controls -->
    <div class="button-controls">
      <button id="incrementer" class="btn btn-main" @click="incrementCounter();">Increment Counter</button>
      <button id="resetter" class="btn btn-alt" @click="resetCounter();">Reset Counter</button>
    </div>

    <!-- Loading -->
    <div class="loading" v-if="loading.status">
      <p v-if="loading.msg">{{loading.msg}}</p>
    </div>

    <div class="logs" v-if="logs.length">
      <div v-for="(log,i) in logs" :key="i">
        <p class="label" v-if="log.timestamp">
          <strong><span v-if="log.increment">Counter Incremented&nbsp;</span><span v-if="log.reset">Counter Reset&nbsp;</span>({{log.timestamp}}):</strong>
        </p>
        <pre class="log-entry">{{ log }}</pre>
      </div>
    </div>
  </div>
</template>

<script>
import {SigningArchwayClient} from "@archwayhq/arch3-core";
import { calculateFee, GasPrice } from "@cosmjs/stargate";
import { ConstantineInfo } from './chain.info.constantine';

const RPC = ConstantineInfo.rpc;
const ContractAddress = "archway1zvhyd8wqlwpvl6pn8fdlkc9vmsvhmlnls3edrcvlxp5gykgm54tsva96hs";

export default {
  name: "App",
  data: () => ({
    contract: ContractAddress,
    counter: null,
    cwClient: null,
    chainMeta: ConstantineInfo,
    offlineSigner: null,
    gas: {
      price: null
    },
    handlers: {
      query: null
    },
    loading: {
      status: false,
      msg: ""
    },
    logs: [],
    rpc: RPC,
    accounts: null
  }),
  mounted: async function () {},
  methods: {
    connectWallet: async function () {
      console.log('Connecting wallet...');
      try {
        if (window) {
          if (window['keplr']) {
            if (window.keplr['experimentalSuggestChain']) {
              await window.keplr.experimentalSuggestChain(this.chainMeta)
              await window.keplr.enable(this.chainMeta.chainId);
              this.offlineSigner = await window.getOfflineSigner(this.chainMeta.chainId);
              this.cwClient = await SigningArchwayClient.connectWithSigner(this.rpc, this.offlineSigner);
              this.accounts = await this.offlineSigner.getAccounts();

              console.log('Wallet connected', {
                offlineSigner: this.offlineSigner,
                cwClient: this.cwClient,
                accounts: this.accounts,
                chain: this.chainMeta
              });
              // Query ref.
              this.handlers.query = this.cwClient.queryClient.wasm.queryContractSmart;
              // Gas
              this.gas.price = GasPrice.fromString('0.002uconst');
              // Debug
              console.log('dApp Initialized', {
                user: this.accounts[0].address,
                client: this.cwClient,
                handlers: this.handlers,
                gas: this.gas
              });

              await this.start();
            } else {
              console.warn('Error access experimental features, please update Keplr');
            }
          } else {
            console.warn('Error accessing Keplr');
          }
        } else {
          console.warn('Error parsing window object');
        }
      } catch (e) {
        console.error('Error connecting to wallet', e);
      }
    },
    start: async function () {
      // Get count
      let counter = await this.getCount();
      if (!isNaN(counter.count)) {
        this.counter = counter.count;
        console.log('Counter updated', this.counter);
      } else {
        console.warn('Error expected numeric value from counter, found: ', typeof counter.count);
      }
    },
    /**
     * Query contract counter
     * @see {SigningCosmWasmClient}
     * @see https://github.com/drewstaylor/archway-template/blob/main/src/contract.rs#L66-L71
     */
    getCount: async function () {
      // SigningCosmWasmClient.query: async (address, query)
      let entrypoint = {
        get_count: {}
      };
      this.loading = {
        status: true,
        msg: "Refreshing counter..."
      };
      let query = await this.cwClient.queryContractSmart(this.contract, entrypoint);
      console.log('Counter Queried', query);
      this.loading.status = false;
      this.loading.msg = "";
      return query;
    },
    /**
     * Increment the counter
     * @see {SigningCosmWasmClient}
     * @see https://github.com/drewstaylor/archway-template/blob/main/src/contract.rs#L42
     */
    incrementCounter: async function () {
      // SigningCosmWasmClient.execute: async (senderAddress, contractAddress, msg, fee, memo = "", funds)
      if (!this.accounts) {
        console.warn('Error getting user', this.accounts);
        return;
      } else if (!this.accounts.length) {
        console.warn('Error getting user', this.accounts);
        return;
      }
      // Prepare Tx
      let entrypoint = {
        increment: {}
      };
      this.loading = {
        status: true,
        msg: "Incrementing counter..."
      };
      let txFee = calculateFee(300000, this.gas.price); // XXX TODO: Fix gas estimation (https://github.com/cosmos/cosmjs/issues/828)
      console.log('Tx args', {
        senderAddress: this.accounts[0].address,
        contractAddress: this.contract,
        msg: entrypoint,
        fee: txFee
      });
      try {
        // Send Tx
        let tx = await this.cwClient.execute(this.accounts[0].address, this.contract, entrypoint, txFee);
        this.loading.status = false;
        this.loading.msg = "";
        console.log('Increment Tx', tx);
        // Update Logs
        if (tx.logs) {
          if (tx.logs.length) {
            this.logs.unshift({
              increment: tx.logs,
              timestamp: new Date().getTime()
            });
            console.log('Logs Updated', this.logs);
          }
        }
        // Refresh counter display
        let counter = await this.getCount();
        if (!isNaN(counter.count)) {
          this.counter = counter.count;
        } else {
          console.warn('Error expected numeric value from counter, found: ', typeof counter.count);
        }
      } catch (e) {
        console.warn('Error executing Increment', e);
        this.loading.status = false;
        this.loading.msg = "";
      }
    },
    /**
     * Reset counter to 0
     * @see {SigningCosmWasmClient}
     * @see https://github.com/drewstaylor/archway-template/blob/main/src/contract.rs#L43
     */
    resetCounter: async function () {
      // SigningCosmWasmClient.execute: async (senderAddress, contractAddress, msg, fee, memo = "", funds)
      if (!this.accounts) {
        console.warn('Error getting user', this.accounts);
        return;
      } else if (!this.accounts.length) {
        console.warn('Error getting user', this.accounts);
        return;
      }
      // Prepare Tx
      let entrypoint = {
        reset: {
          count: 0
        }
      };
      this.loading = {
        status: true,
        msg: "Resetting counter..."
      };
      let txFee = calculateFee(300000, this.gas.price); // XXX TODO: Fix gas estimation (https://github.com/cosmos/cosmjs/issues/828)
      // Send Tx
      try {
        let tx = await this.cwClient.execute(this.accounts[0].address, this.contract, entrypoint, txFee);
        console.log('Reset Tx', tx);
        this.loading.status = false;
        this.loading.msg = "";
        // Update Logs
        if (tx.logs) {
          if (tx.logs.length) {
            this.logs.unshift({
              reset: tx.logs,
              timestamp: new Date().getTime()
            });
            console.log('Logs Updated', this.logs);
          }
        }
        // Refresh counter display
        let counter = await this.getCount();
        if (!isNaN(counter.count)) {
          this.counter = counter.count;
        } else {
          console.warn('Error expected numeric value from counter, found: ', typeof counter.count);
        }
      } catch (e) {
        console.warn("Error executing Reset", e);
        this.loading.status = false;
        this.loading.msg = "";
      }
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
div.content {
  text-align: left;
  margin: auto;
  margin-top: 3em;
  width: 90vw;
  max-width: 1280px;
}
div.content ul {
  list-style: none;
  padding-left: 0;
}
button {
  margin: 1rem;
  padding: 0.25rem;
}
p.label {
  padding-bottom: 0;
  margin-bottom: 0;
}
pre {
  line-height:1.2em;
  background:linear-gradient(180deg,#ccc 0,#ccc 1.2em,#eee 0);
  background-size:2.4em 2.4em;
  background-origin:content-box;
  padding: 1em;
  text-align:justify;
  display: inline-block;
  color: #0a4862;
  background-color: #73c8eb;
  border-color: #3bb3e3;
  border-radius: 0.5em;
}
</style>

// react/increment/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import { SigningArchwayClient } from "@archwayhq/arch3-core";
import { calculateFee, GasPrice } from "@cosmjs/stargate";
import { ConstantineInfo } from './chain.info.constantine';

const RPC = ConstantineInfo.rpc;
const ContractAddress = "archway1zvhyd8wqlwpvl6pn8fdlkc9vmsvhmlnls3edrcvlxp5gykgm54tsva96hs";

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      contract: ContractAddress,
      counter: null,
      cwClient: null,
      offlineSigner: null,
      chainMeta: ConstantineInfo,
      gasPrice: null,
      queryHandler: null,
      loadingStatus: false,
      loadingMsg: "",
      logs: [],
      rpc: RPC,
      accounts: null,
      userAddress: null
    };
  };

  /**
   * Instances basic settings
   * @see {File} ./.env
   * @see {File} ./env.example
   * @see https://create-react-app.dev/docs/adding-custom-environment-variables/
   */
   connectWallet = async () => {
    console.log('Connecting wallet...');
      try {
        if (window) {
          if (window['keplr']) {
            if (window.keplr['experimentalSuggestChain']) {
              await window.keplr.experimentalSuggestChain(this.state.chainMeta)
              await window.keplr.enable(this.state.chainMeta.chainId);
              let offlineSigner = await window.getOfflineSigner(this.state.chainMeta.chainId);
              console.log('offlineSigner', offlineSigner);
              let cwClient = await SigningArchwayClient.connectWithSigner(this.state.rpc, offlineSigner);
              let accounts = await offlineSigner.getAccounts();
              let queryHandler = cwClient.queryContractSmart;
              let gasPrice = GasPrice.fromString('0.002uconst');
              let userAddress = accounts[0].address;

              // Update state
              this.setState({
                accounts: accounts,
                userAddress: userAddress,
                cwClient: cwClient,
                queryHandler: queryHandler,
                gasPrice: gasPrice,
                offlineSigner: offlineSigner
              });

              // Debug
              console.log('dApp Connected', {
                accounts: this.state.accounts,
                userAddress: this.state.userAddress,
                client: this.state.cwClient,
                queryHandler: this.state.queryHandler,
                gasPrice: this.state.gasPrice,
                offlineSigner: this.state.offlineSigner
              });

              // Get count
              let counter = await this.getCount();
              try {
                if (!isNaN(counter.count)) {
                  this.setState({ counter: counter.count });
                } else {
                  console.warn('Error expected numeric value from counter, found: ', typeof counter.count);
                }
              } catch (e) {
                console.warn('Error: failed getting counter value', e);
              }
            } else {
              console.warn('Error access experimental features, please update Keplr');
            }
          } else {
            console.warn('Error accessing Keplr');
          }
        } else {
          console.warn('Error parsing window object');
        }
      } catch (e) {
        console.error('Error connecting to wallet', e);
      }
  }

  /**
   * Query contract counter
   * @see {SigningArchwayClient}
   * @see https://github.com/drewstaylor/archway-template/blob/main/src/contract.rs#L66-L71
   */
  getCount = async () => {
    // SigningCosmWasmClient.query: async (address, query)
    let loading;
    loading = {
      status: true,
      msg: "Refreshing counter..."
    };
    this.setState({
      loadingStatus: loading.status,
      loadingMsg: loading.msg
    });
    let entrypoint = {
      get_count: {}
    };
    let query = await this.state.cwClient.queryContractSmart(ContractAddress,entrypoint);
    loading = {
      status: false,
      msg: ""
    };
    this.setState({
      loadingStatus: loading.status,
      loadingMsg: loading.msg
    });
    console.log('Counter Queried', query);
    return query;
  }

  /**
   * Increment the counter
   * @see {SigningArchwayClient}
   * @see https://github.com/drewstaylor/archway-template/blob/main/src/contract.rs#L42
   */
  incrementCounter = async () => {
    // SigningCosmWasmClient.execute: async (senderAddress, contractAddress, msg, fee, memo = "", funds)
    if (!this.state.accounts) {
      console.warn('Error getting accounts', this.state.accounts);
      return;
    } else if (!this.state.userAddress) {
      console.warn('Error getting user address', this.state.userAddress);
      return;
    }
    let loading;
    loading = {
      status: true,
      msg: "Incrementing counter..."
    };
    this.setState({
      loadingStatus: loading.status,
      loadingMsg: loading.msg
    });
    // Prepare Tx
    let entrypoint = {
      increment: {}
    };
    let txFee = calculateFee(300000, this.state.gasPrice); // XXX TODO: Fix gas estimation (https://github.com/cosmos/cosmjs/issues/828)
    console.log('Tx args', {
      senderAddress: this.state.userAddress,
      contractAddress: this.state.contract,
      msg: entrypoint,
      fee: txFee
    });
    // Send Tx
    try {
      let tx = await this.state.cwClient.execute(this.state.userAddress, this.state.contract, entrypoint, txFee);
      console.log('Increment Tx', tx);
      // Update Logs
      if (tx.logs) {
        if (tx.logs.length) {
          tx.logs[0].type = 'increment';
          tx.logs[0].timestamp = new Date().getTime();
          this.setState({
            logs: [JSON.stringify(tx.logs, null, 2), ...this.state.logs]
          });
        }
      }
      // Refresh counter
      let counter = await this.getCount();
      let count;
      if (!isNaN(counter.count)) {
        count = counter.count;
      } else {
        count = this.state.counter;
        console.warn('Error expected numeric value from counter, found: ', typeof counter.count);
      }
      // Render updates
      loading = {
        status: false,
        msg: ""
      };
      this.setState({
        counter: count,
        loadingStatus: loading.status,
        loadingMsg: loading.msg
      });
    } catch (e) {
      console.warn('Error exceuting Increment', e);
      loading = {
        status: false,
        msg: ""
      };
      this.setState({
        loadingStatus: loading.status,
        loadingMsg: loading.msg
      });
    }
  }

  /**
   * Reset counter to 0
   * @see {SigningArchwayClient}
   * @see https://github.com/drewstaylor/archway-template/blob/main/src/contract.rs#L43
   */
  resetCounter = async () => {
    // SigningCosmWasmClient.execute: async (senderAddress, contractAddress, msg, fee, memo = "", funds)
    if (!this.state.accounts) {
      console.warn('Error getting user account', this.state.accounts);
      return;
    } else if (!this.state.userAddress) {
      console.warn('Error getting user address', this.state.userAddress);
      return;
    }
    let loading;
    loading = {
      status: true,
      msg: "Resetting counter..."
    };
    this.setState({
      loadingStatus: loading.status,
      loadingMsg: loading.msg
    });
    // Prepare Tx
    let entrypoint = {
      reset: {
        count: 0
      }
    };
    let txFee = calculateFee(300000, this.state.gasPrice); // XXX TODO: Fix gas estimation (https://github.com/cosmos/cosmjs/issues/828)
    // Send Tx
    try {
      let tx = await this.state.cwClient.execute(this.state.userAddress, this.state.contract, entrypoint, txFee);
      console.log('Reset Tx', tx);
      // Update Logs
      if (tx.logs) {
        if (tx.logs.length) {
          tx.logs[0].type = 'reset';
          tx.logs[0].timestamp = new Date().getTime();
          this.setState({
            logs: [JSON.stringify(tx.logs, null, 2), ...this.state.logs]
          });
        }
      }
      // Refresh counter
      let counter = await this.getCount();
      let count;
      if (!isNaN(counter.count)) {
        count = counter.count;
      } else {
        count = this.state.counter;
        console.warn('Error expected numeric value from counter, found: ', typeof counter.count);
      }
      // Render updates
      loading = {
        status: false,
        msg: ""
      };
      this.setState({
        counter: count,
        loadingStatus: loading.status,
        loadingMsg: loading.msg
      });
    } catch (e) {
      console.warn('Error executing Reset', e);
      loading = {
        status: false,
        msg: ""
      };
      this.setState({
        loadingStatus: loading.status,
        loadingMsg: loading.msg
      });
    }
  }

  render() {
    // State
    const counter = this.state.counter;
    const loadingMsg = this.state.loadingMsg;
    const userAddress = this.state.userAddress;

    // Maps
    let logMeta = [];
    for (let i = 0; i < this.state.logs.length; i++) {
      let logItem = JSON.parse(this.state.logs[i]);
      let meta = {
        type: logItem[0].type,
        timestamp: logItem[0].timestamp
      };
      logMeta.push(meta);
    }
    const logItems = (this.state.logs.length) ? this.state.logs.map((log,i) =>
      <div key={logMeta[i].timestamp}>
        <p className="label">
          <strong><span>Counter {(logMeta[i].type === 'increment') ? 'Incremented' : 'Reset' }&nbsp;</span>({logMeta[i].timestamp}):</strong>
        </p>
        <pre className="log-entry" key={i}>{log}</pre>
      </div>
    ) : null;

    // Not Connected
    if (!userAddress) {
      return (
        <div className="content">
          <img src={logo} alt="logo" />

          <div className="button-controls">
            <button id="connect" className="btn btn-main" onClick={this.connectWallet}>Connect Wallet</button>
          </div>

        </div>
      );
    }

    // Connected
    return (
      <div className="content">
        <img src={logo} alt="logo" />

        {/* Counter Status Display */}
        <div className="status-display">
          <ul className="status">
            <li className="counter"><strong>Counter:</strong>&nbsp;{counter}</li>
          </ul>
        </div>

        {/* Controls */}
        <div className="button-controls">
          <button id="incrementer" className="btn btn-main" onClick={this.incrementCounter}>Increment Counter</button>
          <button id="resetter" className="btn btn-alt" onClick={this.resetCounter}>Reset Counter</button>
        </div>

        {/* Loading */}
        {Loading(loadingMsg)}

        {/* Logs map */}
        <div className="logs">
          <div>{logItems}</div>
        </div>

      </div>
    );
  };

}

// Conditional rendering
function Loading(msg) {
  if (!msg) {
    return;
  }
  return (
    <div className="loading">
      <p>{msg}</p>
    </div>
  );
}
